package com.snaildev;

import com.snaildev.dao.IUserDao;
import com.snaildev.model.UserModel;
import com.snaildev.model.UserModel2;
import org.hibernate.*;
import org.junit.*;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.orm.hibernate5.HibernateCallback;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

public class HibernateTest {
    private static SessionFactory sessionFactory;

    @BeforeClass
    public static void beforeClass() {
        String[] configLoacations = new String[]{
                "classpath:applicationContext-resources.xml",
                "classpath:applicationContext-hibernate.xml"};
        ApplicationContext ctx = new ClassPathXmlApplicationContext(configLoacations);
        sessionFactory = ctx.getBean("sessionFactory", SessionFactory.class);
    }

    @Before
    public void setUp() {
        final String createTableSql = "create memory table test(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100))";
        sessionFactory.openSession().createSQLQuery(createTableSql).executeUpdate();
    }

    @After
    public void tearDown() {
        final String dropTableSql = "drop table test";
        sessionFactory.openSession().createSQLQuery(dropTableSql).executeUpdate();
    }

    @Test
    public void testFirst() {
        Session session = sessionFactory.openSession();
        Transaction transaction = null;
        try {
            transaction = beginTransaction(session);
            UserModel model = new UserModel();
            model.setName("name");
            session.save(model);
        } catch (RuntimeException ex) {
            rollbackTransaction(transaction);
            throw ex;
        } finally {
            commitTransaction(session);
        }
    }

    private void commitTransaction(Session session) {
        session.close();
    }

    private void rollbackTransaction(Transaction transaction) {
        if (transaction != null) {
            transaction.rollback();
        }
    }

    private Transaction beginTransaction(Session session) {
        Transaction transaction = session.beginTransaction();
        transaction.begin();
        return transaction;
    }

    @Test
    // @Transactional(readOnly = true)
    public void testHibernateTemplate() {
        HibernateTemplate hibernateTemplate = new HibernateTemplate(sessionFactory);
        final UserModel model = new UserModel();
        model.setName("xiaoming");
        //hibernateTemplate.save(model);

        //通过回调允许更复杂操作
        hibernateTemplate.execute(new HibernateCallback<Void>() {
            @Override
            public Void doInHibernate(Session session) throws HibernateException {
                session.save(model);
                return null;
            }
        });
    }

    @Test
    public void testBestPractice(){
        String[] configLocations = new String[]{
                "classpath:applicationContext-resources.xml",
                "classpath:applicationContext-hibernate.xml"};
        ApplicationContext ctx = new ClassPathXmlApplicationContext(configLocations);
        IUserDao userDao = ctx.getBean(IUserDao.class);
        UserModel model = new UserModel();
        model.setName("test");
        userDao.save(model);
        Assert.assertEquals(1, userDao.countAll());
    }

    @Test
    public void testCURD() {
        String[] configLocations = new String[] {
                "classpath:applicationContext-resources.xml",
                "classpath:applicationContext-hibernate2.xml"};
        ApplicationContext ctx =  new ClassPathXmlApplicationContext(configLocations);
        HibernateTemplate hibernateTemplate =  ctx.getBean(HibernateTemplate.class);

        UserModel2 model = new UserModel2();
        model.setMyName("test");
        //insert(hibernateTemplate, model);
        //select(hibernateTemplate, model);
        //update(hibernateTemplate, model);
        //delete(hibernateTemplate, model);
    }

    private void insert(HibernateTemplate hibernateTemplate, UserModel2 model) {
        hibernateTemplate.save(model);
    }
    private void select(HibernateTemplate hibernateTemplate, UserModel2 model) {
        UserModel2 model2 = hibernateTemplate.get(UserModel2.class, 0);
        Assert.assertEquals(model2.getMyName(), model.getMyName());
        List<UserModel2> list = (List<UserModel2>) hibernateTemplate.find("from UserModel2");
        Assert.assertEquals(list.get(0).getMyName(), model.getMyName());
    }
    private void update(HibernateTemplate hibernateTemplate, UserModel2 model) {
        model.setMyName("test2");
        hibernateTemplate.update(model);
    }
    private void delete(HibernateTemplate hibernateTemplate, UserModel2 model) {
        hibernateTemplate.delete(model);
    }
}
